name: Publish to npm

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version and publish
        run: |
          VERSION="0.0.0-$(date +%Y%m%d).g$(git rev-parse --short HEAD)"
          npm version $VERSION --no-git-tag-version
          git add package.json package-lock.json
          git commit -m "chore(release): $VERSION"
          git tag "v$VERSION"
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push tag
        run: git push --follow-tags